# -*- coding: utf-8 -*-
"""code.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vpMeiavBL6G6p1HxyIaT0tdCNe6Xjm5K
"""

!pip install ultralytics

from ultralytics import YOLO
import os
import json
from collections import Counter

# If you're in Google Colab, uncomment the following line:
from google.colab import files

# Paths
yaml_path = "/content/drive/MyDrive/cv_roboflow/computer vision_yolov8/data.yaml" # Change this to your actual path
test_images_path = "/content/drive/MyDrive/cv_roboflow/computer vision_yolov8/test/images"    # Update if your test path is different
output_json_path = 'final_counts.json'


# Step 1: Load and Train the Model
model = YOLO('yolov8n.pt')  # Using YOLOv8 nano model, can be changed

# Train
model.train(
    data=yaml_path,
    epochs=30,
    imgsz=640,
    batch=16,
    name='custom_object_detection_model'
)

# Step 2: Load Trained Model
trained_model_path = 'runs/detect/custom_object_detection_model/weights/best.pt'
model = YOLO(trained_model_path)

# Step 3: Run Inference
results = model.predict(test_images_path, save=False)

# Step 4: Parse Inference Results
# Get class names according to your YAML
class_names = ['Product-Name', 'Empty-Space', 'Other-Product']

# Initialize counter
counts = Counter({name: 0 for name in class_names})

for result in results:
    boxes = result.boxes
    for box in boxes:
        cls_id = int(box.cls[0].item())
        cls_name = class_names[cls_id]
        counts[cls_name] += 1

# Step 5: Save Final Counts to JSON
with open(output_json_path, 'w') as f:
    json.dump(counts, f, indent=4)

print(f"Final counts saved to {output_json_path}")
print(counts)

# Step 6: Download the JSON file (only works in Colab)
files.download(output_json_path)

